package Registration;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class PasswordEncrypt {

    private static byte[] getSHA(String input) throws NoSuchAlgorithmException {

        // Use SHA-256 instance and convert input into byte array
        return MessageDigest.getInstance("SHA-256").digest(input.getBytes(StandardCharsets.UTF_8));
    }

    public static String encryptSHA256(String input) {
        
        try {

            // Convert byte array into signum representation
            BigInteger number = new BigInteger(1, getSHA(input));

            // Convert message digest into hex value
            StringBuilder hexString = new StringBuilder(number.toString(16));

            // Pad with leading zeros
            while (hexString.length() < 64) {
                hexString.insert(0, '0');
            }

            return hexString.toString();
        }
        catch (NoSuchAlgorithmException e) { System.out.println("No Such Algorithm Error: " + e); }
        
        return input;
    }

    // Test
    public static void main(String args[]) {

        System.out.println("HashCode Generated by SHA-256 for:");

        String s1 = "pAssword1";
        System.out.println("\n" + s1 + ": " + encryptSHA256(s1));

        String s2 = "mypAssword1";
        System.out.println("\n" + s2 + ": " + encryptSHA256(s2));

        String s3 = "my-pAssword1";
        System.out.println("\n" + s3 + ": " + encryptSHA256(s3));
    }
}
